services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: archive-org-proxy:latest
    container_name: archive-org-proxy
    ports:
      - "18080:80"
    restart: always
